services:
  dashboard:
    build: ${DEFAULT_APPS_MOUNT}/home-server-dashboard
    container_name: home_lab_dashboard
    ports:
      - "${DASHBOARD_PORT}:80"
    restart: always

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${DEFAULT_PUID}
      - PGID=${DEFAULT_GUID}
      - TZ=${DEFAULT_TIMEZONE}
      - VERSION=docker
      - ENABLE_HW_TRANSCODE=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility  
    volumes:
      - ${DEFAULT_APPS_MOUNT}/${PLEX_FOLDER}/config:/config
      - ${DEFAULT_STORAGE_MOUNT}/${PLEX_FOLDER}/transcode:/transcode
      - ${DEFAULT_STORAGE_MOUNT}/${QBITTORRENT_FOLDER}/${QBITTORRENT_DOWNLOADS_FOLDER}:/data
      - /dev/dri:/dev/dri                     
    deploy: 
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    restart: always


  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${DEFAULT_PUID}
      - PGID=${DEFAULT_GUID}
      - TZ=${DEFAULT_TIMEZONE}
      - WEBUI_PORT=${QBITTORRENT_UI_PORT}
      - TORRENTING_PORT=${QBITTORRENT_TORRENTING_PORT}
    volumes:
      - ${DEFAULT_APPS_MOUNT}/${QBITTORRENT_FOLDER}/config:/config
      - ${DEFAULT_STORAGE_MOUNT}/${QBITTORRENT_FOLDER}/${QBITTORRENT_DOWNLOADS_FOLDER}:/${QBITTORRENT_DOWNLOADS_FOLDER}
    ports:
      - "${QBITTORRENT_UI_PORT}:${QBITTORRENT_UI_PORT}"
      - "${QBITTORRENT_TORRENTING_PORT}:${QBITTORRENT_TORRENTING_PORT}"
      - "${QBITTORRENT_TORRENTING_PORT}:${QBITTORRENT_TORRENTING_PORT}/udp"

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    ports:
      - "${FILEBROWSER_UI_PORT}:80"
    volumes:
      - ${DEFAULT_APPS_MOUNT}/${FILEBROWSER_FOLDER}/config:/config
      - ${DEFAULT_STORAGE_MOUNT}/:/srv
    restart: always
    environment:
      - PUID=${DEFAULT_PUID}
      - PGID=${DEFAULT_GUID}

  samba:
    image: dockurr/samba:4.22.6
    container_name: samba
    environment:
      NAME: "${SAMBA_SHARE_NAME}"
      USER: "${SAMBA_USERNAME}"
      PASS: "${SAMBA_PASSWORD}"
      PUID: "${DEFAULT_PUID}"
      PGID: "${DEFAULT_GUID}"
    ports:
      - "${SAMBA_PORT}:445"
    volumes:
      - ${DEFAULT_STORAGE_MOUNT}:/storage
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${DEFAULT_PUID}
      - PGID=${DEFAULT_GUID}
      - TZ=${DEFAULT_TIMEZONE}
    volumes:
      - ${DEFAULT_APPS_MOUNT}/${SONARR_FOLDER}/config:/config
      - ${DEFAULT_STORAGE_MOUNT}/${QBITTORRENT_FOLDER}/${QBITTORRENT_DOWNLOADS_FOLDER}/${QBITTORRENT_TV_FOLDER}:/${SONARR_TV_FOLDER}
      - ${DEFAULT_STORAGE_MOUNT}/${QBITTORRENT_FOLDER}/${QBITTORRENT_DOWNLOADS_FOLDER}/${QBITTORRENT_MOVIES_FOLDER}:/${SONARR_MOVIES_FOLDER}
      - ${DEFAULT_STORAGE_MOUNT}/${QBITTORRENT_FOLDER}/${QBITTORRENT_DOWNLOADS_FOLDER}/:/downloads
    ports:
      - "${SONARR_PORT}:8989"
    restart: always

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${DEFAULT_PUID}
      - PGID=${DEFAULT_GUID}
      - TZ=${DEFAULT_TIMEZONE}
    volumes:
      - ${DEFAULT_APPS_MOUNT}/${RADARR_FOLDER}/config:/config
      - ${DEFAULT_STORAGE_MOUNT}/${QBITTORRENT_FOLDER}/${QBITTORRENT_DOWNLOADS_FOLDER}/${QBITTORRENT_TV_FOLDER}:/${RADARR_TV_FOLDER}
      - ${DEFAULT_STORAGE_MOUNT}/${QBITTORRENT_FOLDER}/${QBITTORRENT_DOWNLOADS_FOLDER}/${QBITTORRENT_MOVIES_FOLDER}:/${RADARR_MOVIES_FOLDER}
      - ${DEFAULT_STORAGE_MOUNT}/${QBITTORRENT_FOLDER}/${QBITTORRENT_DOWNLOADS_FOLDER}/:/downloads
    ports:
        - "${RADARR_PORT}:7878"
    restart: always

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${DEFAULT_PUID}
      - PGID=${DEFAULT_GUID}
      - TZ=${DEFAULT_TIMEZONE}
    volumes:
      - ${DEFAULT_APPS_MOUNT}/${JACKETT_FOLDER}/config:/config
      - ${DEFAULT_STORAGE_MOUNT}/${QBITTORRENT_FOLDER}/${QBITTORRENT_DOWNLOADS_FOLDER}/${QBITTORRENT_TV_FOLDER}:/${JACKETT_TV_FOLDER}
      - ${DEFAULT_STORAGE_MOUNT}/${QBITTORRENT_FOLDER}/${QBITTORRENT_DOWNLOADS_FOLDER}/${QBITTORRENT_MOVIES_FOLDER}:/${JACKETT_MOVIES_FOLDER}
      - ${DEFAULT_STORAGE_MOUNT}/${QBITTORRENT_FOLDER}/${QBITTORRENT_DOWNLOADS_FOLDER}/:/downloads
    ports:
        - "${JACKETT_PORT}:9117"
    restart: always

  maintainerr:
      image: ghcr.io/maintainerr/maintainerr:latest
      container_name: maintainerr
      user: "${DEFAULT_PUID}:${DEFAULT_GUID}"
      volumes:
        - type: bind
          source: ${DEFAULT_STORAGE_MOUNT}/${MAINTAINERR_FOLDER}/data
          target: /opt/data
      environment:
        - TZ=${DEFAULT_TIMEZONE}
      ports:
        - "${MAINTAINERR_PORT}:6246"
      restart: always

  couchdb:
    image: couchdb:3.5
    container_name: couchdb-for-ols
    user: "${DEFAULT_PUID}:${DEFAULT_GUID}"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ${DEFAULT_APPS_MOUNT}/${COUCHDB_FOLDER}/couchdb-data:/opt/couchdb/data
      - ${DEFAULT_APPS_MOUNT}/${COUCHDB_FOLDER}/couchdb-etc:/opt/couchdb/etc/local.d
    ports:
      - "${COUCHDB_PORT}:5984"
    restart: always

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    cap_add:
      - NET_ADMIN
    environment:
      TZ: '${DEFAULT_TIMEZONE}'
      PIHOLE_UID: '${DEFAULT_PUID}'
      PIHOLE_GID: '${DEFAULT_GUID}'
      WEBPASSWORD: '${PI_HOLE_WEB_PASSWORD}'
      FTLCONF_webserver_api_password: '${PI_HOLE_WEB_PASSWORD}'
      DNSMASQ_LISTENING: 'all'
    dns:
      - 127.0.0.1
      - ${PI_HOLE_DEFAULT_DNS}
    volumes:
      - ${DEFAULT_APPS_MOUNT}/${PI_HOLE_FOLDER}/${PI_HOLE_FOLDER}/:/etc/pihole
      - ${DEFAULT_APPS_MOUNT}/${PI_HOLE_FOLDER}/${PI_HOLE_DNSMASQ_FOLDER}:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${PI_HOLE_UI_PORT}:80/tcp"
    restart: unless-stopped

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    environment:
      - LOG_LEVEL=debug
      - TZ='${DEFAULT_TIMEZONE}'
      - PORT=${SEERR_PORT}
      - PUID=${DEFAULT_PUID}
      - PGID=${DEFAULT_GUID}
    ports:
      - "${SEERR_PORT}:5055"
    volumes:
      - ${DEFAULT_APPS_MOUNT}/${SEERR_FOLDER}/config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ='${DEFAULT_TIMEZONE}'
    ports:
      - "${FLARESOLVERR_PORT}:8191"
    restart: unless-stopped 

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ${DEFAULT_APPS_MOUNT}/${OLLAMA_FOLDER}:/root/.ollama
    environment:
      - PUID=${DEFAULT_PUID}
      - PGID=${DEFAULT_GUID}
      - TZ=${DEFAULT_TIMEZONE}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    restart: unless-stopped

  mattermost-db:
    image: postgres:14-alpine
    container_name: mattermost_db
    environment:
      - POSTGRES_USER=${MATTERMOST_DB_USER}
      - POSTGRES_PASSWORD=${MATTERMOST_DB_PASSWORD}
      - POSTGRES_DB=${MATTERMOST_DB_NAME}
    volumes:
      - ${DEFAULT_APPS_MOUNT}/${MATTERMOST_FOLDER}/db:/var/lib/postgresql/data
    restart: always

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost
    user: "2000:2000"
    ports:
      - "${MATTERMOST_PORT}:8065"
    environment:
      - TZ=${DEFAULT_TIMEZONE}
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://${MATTERMOST_DB_USER}:${MATTERMOST_DB_PASSWORD}@mattermost-db:${MATTERMOST_DB_PORT}/${MATTERMOST_DB_NAME}?sslmode=disable&connect_timeout=10
    volumes:
      - ${DEFAULT_APPS_MOUNT}/${MATTERMOST_FOLDER}/data:/mattermost/data
      - ${DEFAULT_APPS_MOUNT}/${MATTERMOST_FOLDER}/logs:/mattermost/logs
      - ${DEFAULT_APPS_MOUNT}/${MATTERMOST_FOLDER}/config:/mattermost/config
    depends_on:
      - mattermost-db
    restart: always

  qdirstat:
    image: jlesage/qdirstat
    container_name: qdirstat
    ports:
      - "${QDirstat_PORT}:5800"
    volumes:
      - ${DEFAULT_APPS_MOUNT}/${QDirstat_FOLDER}/config:/config
      - ${DEFAULT_STORAGE_MOUNT}:/storage
    restart: always